kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: node:14
    volumes:
      - name: npmcache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn config set registry https://registry.npmmirror.com
      - yarn
      - yarn build
    environment:
      CI: false

  - name: deploy
    image: node:14
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/hospital/
      - cp -rf ./build/* /webroot/hospital/

volumes:
  - name: webroot
    host:
      path: /var/www
  - name: npmcache
    host:
      path: /data/npmcache

trigger:
  branch:
    - master
